# Generated by Django 5.0.13 on 2025-04-18 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_options_user_avatar_user_role_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-date_joined'], 'permissions': [('can_export_pdf', 'Может экспортировать в PDF'), ('manage_private_templates', 'Доступ к приватным шаблонам'), ('moderate_content', 'Может модерировать контент'), ('invite_editors', 'Может приглашать редакторов')], 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Рекомендуемый размер: 200x200 px', null=True, upload_to='users/avatars/%Y/%m/', verbose_name='Аватар'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(help_text='Будет использоваться для входа в систему', max_length=254, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Отключенные пользователи не могут войти в систему', verbose_name='Активный'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, help_text='Формат: +79991234567', max_length=35, null=True, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('GUEST', 'Гость'), ('USER', 'Пользователь'), ('CREATOR', 'Создатель'), ('EDITOR', 'Редактор'), ('MODERATOR', 'Модератор'), ('ADMIN', 'Администратор')], default='USER', help_text='Определяет права пользователя в системе', max_length=10, verbose_name='Роль'),
        ),
        migrations.AlterField(
            model_name='user',
            name='telegram',
            field=models.CharField(blank=True, help_text='Без @, например: username', max_length=150, null=True, verbose_name='Telegram'),
        ),
    ]
