# Generated by Django 5.0.13 on 2025-07-02 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_third_name_alter_user_first_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-date_joined'], 'permissions': [('can_export_pdf', 'Может экспортировать в PDF'), ('can_export_json', 'Может экспортировать в JSON'), ('manage_private_templates', 'Доступ к приватным шаблонам'), ('moderate_content', 'Может модерировать контент'), ('invite_editors', 'Может приглашать редакторов')], 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('USER', 'Пользователь'), ('CREATOR', 'Создатель'), ('EDITOR', 'Редактор'), ('MODERATOR', 'Модератор'), ('ADMIN', 'Администратор')], default='USER', help_text='Определяет права пользователя в системе', max_length=10, verbose_name='Роль'),
        ),
    ]
