# Generated by Django 5.0.13 on 2025-07-02 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_options_alter_user_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-date_joined'], 'permissions': [('can_invite_users', 'Может приглашать новых пользователей'), ('can_manage_users', 'Может управлять пользователями')], 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('CREATOR', 'Креатор'), ('EDITOR', 'Редактор'), ('MODERATOR', 'Модератор'), ('ADMIN', 'Администратор'), ('USER', 'Пользователь')], default='USER', help_text='Определяет права пользователя в системе', max_length=10, verbose_name='Роль'),
        ),
    ]
