# Generated by Django 5.0.13 on 2025-04-19 00:38

import cards.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CardTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Максимальная длина — 100 символов', max_length=100, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Название шаблона')),
                ('fields', models.JSONField(help_text='JSON-структура с описанием полей карточки', validators=[cards.models.validate_fields_structure], verbose_name='Поля шаблона')),
                ('preview_image', models.ImageField(blank=True, help_text='Изображение для предпросмотра шаблона', null=True, upload_to='card_templates/previews/%Y/%m/%d/', verbose_name='Превью шаблона')),
                ('is_public', models.BooleanField(default=False, help_text='Доступен ли шаблон всем пользователям', verbose_name='Публичный доступ')),
                ('description', models.TextField(blank=True, help_text='Подробное описание шаблона', verbose_name='Описание')),
                ('is_favorite', models.BooleanField(default=False, help_text='Помечен ли шаблон как избранный', verbose_name='Избранное')),
                ('is_active', models.BooleanField(default=True, help_text='Активен ли шаблон (мягкое удаление)', verbose_name='Активный')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('creator', models.ForeignKey(help_text='Пользователь, создавший этот шаблон', on_delete=django.db.models.deletion.CASCADE, related_name='templates', to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
                ('editors', models.ManyToManyField(blank=True, help_text='Пользователи с правами редактирования', related_name='editable_templates', to=settings.AUTH_USER_MODEL, verbose_name='Редакторы')),
            ],
            options={
                'verbose_name': 'Шаблон карточки',
                'verbose_name_plural': 'Шаблоны карточек',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CardInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(help_text='Заполненные данные согласно структуре шаблона', verbose_name='Данные карточки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_cards', to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='cards.cardtemplate', verbose_name='Шаблон')),
            ],
            options={
                'verbose_name': 'Экземпляр карточки',
                'verbose_name_plural': 'Экземпляры карточек',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='cardtemplate',
            index=models.Index(fields=['name'], name='cards_cardt_name_6a52e5_idx'),
        ),
        migrations.AddIndex(
            model_name='cardtemplate',
            index=models.Index(fields=['is_public', 'is_active'], name='cards_cardt_is_publ_64c6c8_idx'),
        ),
        migrations.AddConstraint(
            model_name='cardtemplate',
            constraint=models.UniqueConstraint(fields=('name', 'creator'), name='unique_template_name_per_creator'),
        ),
        migrations.AddIndex(
            model_name='cardinstance',
            index=models.Index(fields=['template', 'created_at'], name='cards_cardi_templat_7083e9_idx'),
        ),
    ]
