# Generated by Django 5.0.13 on 2025-04-07 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardtemplate',
            name='preview_image',
            field=models.ImageField(blank=True, null=True, upload_to='previews/', verbose_name='Превью шаблона'),
        ),
    ]
