# Generated by Django 5.0.13 on 2025-04-22 01:53

from django.db import migrations

def remove_image_files(apps, schema_editor):
    CardTemplate = apps.get_model('cards', 'CardTemplate')
    for template in CardTemplate.objects.exclude(preview_image=''):
        template.preview_image.delete(save=False)

class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardtemplate',
            name='preview_image',
        ),
        migrations.RunPython(remove_image_files),
    ]
