# Generated by Django 5.0.13 on 2025-04-22 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_remove_cardtemplate_preview_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardtemplate',
            name='version',
            field=models.PositiveIntegerField(default=1, help_text='Текущая версия шаблона', verbose_name='Версия'),
        ),
    ]
