# Generated by Django 5.0.13 on 2025-04-22 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_cardtemplate_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardinstance',
            name='meta_data',
            field=models.JSONField(blank=True, default=dict, help_text='Дополнительные данные, например, источник, версия шаблона и др.', null=True, verbose_name='Метаданные'),
        ),
    ]
