# Generated by Django 5.0.13 on 2025-04-14 18:05

import cards.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_cardinstance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardtemplate',
            name='fields',
            field=models.JSONField(help_text='\n            JSON-структура с описанием полей. Пример:\n            {\n                "image": {\n                    "type": "image",\n                    "label": "Изображение",\n                    "max_size": 1024\n                },\n                "question": {\n                    "type": "text",\n                    "label": "Вопрос",\n                    "max_length": 200\n                }\n            }\n        ', validators=[cards.models.validate_fields_structure], verbose_name='Поля шаблона'),
        ),
    ]
