# Generated by Django 5.0.13 on 2025-07-02 21:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0004_cardinstance_meta_data'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cardinstance',
            options={'ordering': ['-created_at'], 'permissions': [('can_export_pdf', 'Можно экспортировать в PDF'), ('can_export_json', 'Можно экспортировать в JSON'), ('moderate_content', 'Может модерировать контент'), ('view_public_templates', 'Может просматривать публичные шаблоны')], 'verbose_name': 'Экземпляр карточки', 'verbose_name_plural': 'Экземпляры карточек'},
        ),
        migrations.AlterModelOptions(
            name='cardtemplate',
            options={'ordering': ['-created_at'], 'permissions': [('can_export_pdf', 'Можно экспортировать в PDF'), ('can_export_json', 'Можно экспортировать в JSON'), ('can_change_template', 'Можно изменить шаблон'), ('can_delete_template', 'Можно удалить шаблон'), ('view_public_templates', 'Можно просматривать публичные шаблоны')], 'verbose_name': 'Шаблон карточки', 'verbose_name_plural': 'Шаблоны карточек'},
        ),
        migrations.RemoveIndex(
            model_name='cardtemplate',
            name='cards_cardt_is_publ_64c6c8_idx',
        ),
        migrations.RemoveField(
            model_name='cardtemplate',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='cardtemplate',
            name='version',
        ),
        migrations.AlterField(
            model_name='cardtemplate',
            name='description',
            field=models.TextField(blank=True, help_text='Краткое описание шаблона', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='cardtemplate',
            name='editors',
            field=models.ManyToManyField(blank=True, help_text='Пользователи, имеющие право редактировать шаблон', related_name='editable_templates', to=settings.AUTH_USER_MODEL, verbose_name='Редакторы'),
        ),
        migrations.AlterField(
            model_name='cardtemplate',
            name='is_favorite',
            field=models.BooleanField(default=False, help_text='Пометить шаблон как избранное', verbose_name='Избранное'),
        ),
        migrations.AddIndex(
            model_name='cardtemplate',
            index=models.Index(fields=['is_public', 'is_favorite'], name='cards_cardt_is_publ_4f89aa_idx'),
        ),
    ]
